import {IPost} from "@lib/post/domain/post.interface";
import {randomStringGenerator} from "@nestjs/common/utils/random-string-generator.util";
import {AggregateRoot} from "@nestjs/cqrs";


export class PostAggregate extends AggregateRoot implements IPost {
    id: string = randomStringGenerator();
    title: string;
    message: string;
    authorId: string
    published = false;
    createdAt = new Date().toISOString();
    updatedAt = new Date().toISOString();


    private constructor() {
        super();
    }

    static create(post: Partial<IPost>) {
        const _post = new PostAggregate();
        /** Combine _post which was generated by PostAggregate() and post from param,
         if id is null, id will be generated by PostAggregate, if no, id will be used from post parameter */
        Object.assign(_post, post);

        return _post;
    }
}